from django.urls import path
from  . import views

urlpatterns =[
    path('', views.index, name='index'),
    path ('profil/<id>/view',views.view_profil, name ='viewprofil'),
    path('profil/<id>/update',views.update_profil, name = 'updateprofil'),
    path('profil/<id>/delete',views.delete_profil, name = 'deleteprofil'),
    path('bebanluar/', views.set_beban_luar, name='setbebanluar'),
    path('bebanluar/dinding/', views.set_bl_dinding, name='setdinding'),
    path ('bebanluar/dinding/<id>/view',views.view_dinding, name ='viewdinding'),
    path('bebanluar/dinding/<id>/update',views.update_dinding, name = 'updatedinding'),
    path('bebanluar/dinding/<id>/delete',views.delete_dinding, name = 'deletedinding'),
    path('bebanluar/pintu/', views.set_bl_pintu, name='setpintu'),
    path ('bebanluar/pintu/<id>/view',views.view_pintu, name ='viewpintu'),
    path('bebanluar/pintu/<id>/update',views.update_pintu, name = 'updatepintu'),
    path('bebanluar/pintu/<id>/delete',views.delete_pintu, name = 'deletepintu'),
    path('bebanluar/kaca/', views.set_bl_kaca, name='setkaca'),
    path('bebanluar/kaca/<id>/view', views.view_kaca, name='viewkaca'),
    path('bebanluar/kaca/<id>/update', views.update_kaca, name='updatekaca'),
    path('bebanluar/kaca/<id>/delete', views.delete_kaca, name='deletekaca'),
    path('bebanluar/beton/', views.set_bl_beton, name='setbeton'),
    path ('bebanluar/beton/<id>/view',views.view_beton, name ='viewbeton'),
    path('bebanluar/beton/<id>/update',views.update_beton, name = 'updatebeton'),
    path('bebanluar/beton/<id>/delete',views.delete_beton, name = 'deletebeton'),
    path('bebandalam/', views.set_beban_dalam, name='setbebandalam'),
    path('bebandalam/penghuni', views.set_bd_penghuni, name='setpenghuni'),
    #path ('bebandalam/penghuni/<id>/view',views.view_penghuni, name ='viewpenghuni'),
    path('bebandalam/penghuni/<id>/update',views.update_penghuni, name = 'updatepenghuni'),
    path('bebandalam/penghuni/<id>/delete',views.delete_penghuni, name = 'deletepenghuni'),
    path('bebandalam/cahaya', views.set_bd_cahaya, name='setcahaya'),
    #path ('bebandalam/dinding/<id>/view',views.view_cahaya, name ='viewcahaya'),
    path('bebandalam/cahaya/<id>/update',views.update_cahaya, name = 'updatecahaya'),
    path('bebandalam/cahaya/<id>/delete',views.delete_cahaya, name = 'deletecahaya'),
    path('bebandalam/alat', views.set_bd_alat, name='setalat'),
    path ('bebandalam/alat/<id>/view',views.view_alat, name ='viewalat'),
    path('bebandalam/alat/<id>/update',views.update_alat, name = 'updatealat'),
    path('bebandalam/alat/<id>/delete',views.delete_alat, name = 'deletealat'),
    path('bebaninvvent/', views.set_infiltrasi_ventilasi, name='setinfiltrasiventilasi'),
    #path ('bebaninvvent/<id>/view',views.view_infven, name ='viewinfvent'),
    path('bebaninvvent/<id>/update',views.update_infven, name = 'updateinfvent'),
    path('bebaninvvent/<id>/delete',views.delete_infven, name = 'deleteinfvent'),
    ##path('cacl/bl', views.calc_bk_luar, name='caclbebanluar'),
    path('cacl/bt', views.calculate_beban_kalor_total, name='caclbebantotal'),
    path('cacl/bresume', views.calculate_beban_kalor_resume, name='caclbebanresume'),
    path('cacl/bd', views.calc_bk_dalam, name='calcbebandalam'),
    path('cacl/binv', views.calc_bk_infvent, name='calcinfandvent'),
    path('profile/', views.view_spek, name='viewspek'),

    ]