# Generated by Django 4.1.3 on 2023-01-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfilGedung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("alamat_lokasi", models.CharField(max_length=150)),
                ("lintang", models.FloatField(default=0, max_length=5)),
                (
                    "posisi_lintang",
                    models.CharField(
                        choices=[("LS", "Lintang Selatan"), ("LU", "Lintang Utara")],
                        default="LU",
                        max_length=50,
                    ),
                ),
                ("bujur", models.FloatField(default=0, max_length=5)),
                (
                    "posisi_bujur",
                    models.CharField(
                        choices=[("BB", "Bujur Barat"), ("BT", "Bujur Timur")],
                        default="BB",
                        max_length=50,
                    ),
                ),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tinggi", models.FloatField(max_length=5)),
                ("temperatur_rh", models.FloatField(max_length=5)),
                ("temperatur_obj", models.FloatField(max_length=5)),
                ("kecepatan_angin", models.FloatField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuarPintu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                (
                    "sisi",
                    models.CharField(
                        choices=[
                            ("sisi_1", "Sisi 1"),
                            ("sisi_2", "Sisi 2"),
                            ("sisi_3", "Sisi 3"),
                            ("sisi_4", "Sisi 5"),
                        ],
                        max_length=15,
                    ),
                ),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("awal_kontak_matahari", models.IntegerField(default=0, max_length=1)),
                ("akhir_kontak_matahari", models.IntegerField(default=0, max_length=1)),
                (
                    "temp_rerata_ruang_berdekatan",
                    models.FloatField(default=0, max_length=5),
                ),
                ("material", models.CharField(max_length=50)),
                ("frekwensi_buka_tutup", models.IntegerField()),
                ("waktu_pintu_terbuka", models.FloatField(max_length=5)),
                ("tahanan_thermal", models.FloatField(max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuarKaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                (
                    "sisi",
                    models.CharField(
                        choices=[
                            ("sisi_1", "Sisi 1"),
                            ("sisi_2", "Sisi 2"),
                            ("sisi_3", "Sisi 3"),
                            ("sisi_4", "Sisi 5"),
                        ],
                        max_length=15,
                    ),
                ),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("awal_kontak_matahari", models.IntegerField(default=0)),
                ("akhir_kontak_matahari", models.IntegerField(default=0)),
                ("material", models.CharField(max_length=50)),
                ("arah", models.CharField(max_length=50)),
                (
                    "temp_rerata_ruang_berdekatan",
                    models.FloatField(default=0, max_length=5),
                ),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuarDinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                (
                    "sisi",
                    models.CharField(
                        choices=[
                            ("sisi_1", "Sisi 1"),
                            ("sisi_2", "Sisi 2"),
                            ("sisi_3", "Sisi 3"),
                            ("sisi_4", "Sisi 4"),
                        ],
                        max_length=15,
                    ),
                ),
                ("arah", models.CharField(default="timur", max_length=15)),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("awal_kontak_matahari", models.IntegerField(default=0)),
                ("akhir_kontak_matahari", models.IntegerField(default=0)),
                (
                    "temp_rerata_ruang_berdekatan",
                    models.FloatField(default=0, max_length=5),
                ),
                ("material", models.CharField(max_length=50)),
                ("tahanan_thermal", models.FloatField(max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuarCeiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("kontak_matahari", models.CharField(max_length=1)),
                ("material", models.CharField(max_length=50)),
                ("tahanan_thermal", models.FloatField(max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuarBeton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                (
                    "sisi",
                    models.CharField(
                        choices=[
                            ("sisi_1", "Sisi 1"),
                            ("sisi_2", "Sisi 2"),
                            ("sisi_3", "Sisi 3"),
                            ("sisi_4", "Sisi 4"),
                        ],
                        max_length=15,
                    ),
                ),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("material", models.CharField(max_length=50)),
                ("tahanan_thermal", models.FloatField(max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanLuar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("dinding", "dinding"),
                            ("kaca", "kaca"),
                            ("pintu", "pintu"),
                            ("ceiling", "ceiling"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sisi", models.CharField(default="notspecified", max_length=15)),
                ("dim_panjang", models.FloatField(max_length=5)),
                ("dim_lebar", models.FloatField(max_length=5)),
                ("dim_tebal", models.FloatField(max_length=5)),
                ("kontak_matahari", models.CharField(max_length=1)),
                ("material", models.CharField(max_length=50)),
                ("tahanan_thermal", models.FloatField(max_length=5)),
                (
                    "rasio_kelembaban_udara_ruangan",
                    models.FloatField(default=0, max_length=5),
                ),
                (
                    "rasio_kelembaban_udara_luar",
                    models.FloatField(default=0, max_length=5),
                ),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanInfiltrasiVentilasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField()),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                ("jumlah_stop_kontak", models.IntegerField()),
                ("kec_angin_luar", models.FloatField(max_length=5)),
                (
                    "kelas_shielding",
                    models.CharField(default="shielding 1", max_length=20),
                ),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanDalamPeralatan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                ("jenis_alat", models.CharField(max_length=50)),
                ("beban", models.FloatField(max_length=5)),
                ("jumlah", models.IntegerField(default=0)),
                ("lama_penggunaan", models.FloatField(default=0, max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanDalamPenghuni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                ("aktivitas", models.CharField(default="None", max_length=50)),
                ("jumlah_penghuni", models.IntegerField()),
                ("lama_aktivitas", models.FloatField(default=0, max_length=5)),
                ("total_aktivitas", models.FloatField(default=0, max_length=5)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BebanDalamPencahayaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_lantai", models.IntegerField(default=1)),
                ("nama_ruang", models.CharField(default="ruang1", max_length=50)),
                ("jenis_lampu", models.IntegerField()),
                ("jumlah_lampu", models.IntegerField()),
                ("warna_cat", models.CharField(default="putih", max_length=10)),
                (
                    "gedung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bebankalor.profilgedung",
                    ),
                ),
            ],
        ),
    ]
