# Generated by Django 4.1.3 on 2023-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bebankalor", "0002_rename_dim_lebar_bebanluar_dim_luas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bebanluardinding",
            name="kategori",
            field=models.CharField(
                choices=[("pokok", "pokok"), ("tambahan", "tambahan")],
                default="pokok",
                max_length=50,
            ),
        ),
    ]
