# Generated by Django 4.1.3 on 2023-02-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bebankalor", "0004_bebanluarbeton_akhir_kontak_matahari_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bebanluarbeton",
            name="arah",
            field=models.CharField(default="", max_length=15),
        ),
    ]
