# Generated by Django 4.1.3 on 2023-02-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bebankalor", "0007_bebandalampenghuni_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilgedung",
            name="nama_ruang",
            field=models.CharField(default="sekolah, kelas", max_length=50),
        ),
        migrations.AlterField(
            model_name="bebandalampenghuni",
            name="state",
            field=models.CharField(default="tdk merokok", max_length=50),
        ),
        migrations.AlterField(
            model_name="bebaninfiltrasiventilasi",
            name="nama_ruang",
            field=models.CharField(default="sekolah, kelas", max_length=50),
        ),
    ]
