# Generated by Django 4.1.3 on 2023-02-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bebankalor", "0009_remove_profilgedung_nama_ruang"),
    ]

    operations = [
        migrations.AddField(
            model_name="bebanluarkaca",
            name="sub_kategori_material",
            field=models.CharField(default="tebal", max_length=50),
        ),
    ]
