# Generated by Django 4.1.3 on 2023-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bebankalor", "0010_bebanluarkaca_sub_kategori_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="bebanluarkaca",
            name="jenis_frame",
            field=models.CharField(default="Al", max_length=50),
        ),
        migrations.AddField(
            model_name="bebanluarkaca",
            name="jumlah_lapisan",
            field=models.CharField(default="single_glass", max_length=50),
        ),
        migrations.AlterField(
            model_name="bebanluarbeton",
            name="sisi",
            field=models.CharField(
                choices=[
                    ("sisi_barat", "Sisi Barat"),
                    ("sisi_selatan", "Sisi Selatan"),
                    ("sisi_timur", "Sisi Timur"),
                    ("sisi_utara", "Sisi Utara"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bebanluardinding",
            name="sisi",
            field=models.CharField(
                choices=[
                    ("sisi_barat", "Sisi Barat"),
                    ("sisi_selatan", "Sisi Selatan"),
                    ("sisi_timur", "Sisi Timur"),
                    ("sisi_utara", "Sisi Utara"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bebanluarkaca",
            name="sisi",
            field=models.CharField(
                choices=[
                    ("sisi_barat", "Sisi Barat"),
                    ("sisi_selatan", "Sisi Selatan"),
                    ("sisi_timur", "Sisi Timur"),
                    ("sisi_utara", "Sisi Utara"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="bebanluarkaca",
            name="sub_kategori_material",
            field=models.CharField(default="tirai gulung sedang", max_length=50),
        ),
        migrations.AlterField(
            model_name="bebanluarpintu",
            name="sisi",
            field=models.CharField(
                choices=[
                    ("sisi_barat", "Sisi Barat"),
                    ("sisi_selatan", "Sisi Selatan"),
                    ("sisi_timur", "Sisi Timur"),
                    ("sisi_utara", "Sisi Utara"),
                ],
                max_length=15,
            ),
        ),
    ]
